-------------------------------------------------------------------------------
Test set: HomePage
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 35.866 s <<< FAILURE! - in HomePage
get login user name(HomePage)  Time elapsed: 0.235 s  <<< ERROR!
java.lang.NullPointerException

get login user name(HomePage)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException

get Broken Links(HomePage)  Time elapsed: 35.628 s  <<< ERROR!
org.openqa.selenium.NoSuchSessionException: 
invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'PORTMYTECH-PC-1', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.101, chrome: {chromedriverVersion: 91.0.4472.101 (af52a90bf870..., userDataDir: C:\Users\PORTMY~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:59988}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ba7202f36d79658cfebe717ec9038a53

get Broken Links(HomePage)  Time elapsed: 0 s  <<< ERROR!
org.openqa.selenium.WebDriverException: 
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:16046
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'PORTMYTECH-PC-1', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: driver.version: RemoteWebDriver
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:16046
Caused by: java.net.ConnectException: Connection refused: connect

